server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${DATASOURCE_DB:ticketdb}
    username: ${DATASOURCE_USERNAME:ticketuser}
    password: ${DATASOURCE_PASSWORD:ticketpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

